### PR TITLE
Add feature - connect to existing instance of application (on selected port) / Add keyword "conect to application"

### PR DESCRIPTION
**Pull request by jakubkorepta**
This pull requests include features to connect to existing instance of application hosted on local and self-defined hosts on selected port.

### CODE REVIEW

**Comment by suzukieng** [comment]
Nice, exactly what I'm looking for (and actually have started implemeting myself, based on #17 and #18).
Would be really nice if this could find its way into the mainline.

**Comment by suzukieng** [comment]
Another observation: the connect to application keyword currently only allows to connect to started application on the same host (127.0.0.1):

```
     def _application_started(self, alias, timeout=60, name_contains=None, accept_old=True):
         self.TIMEOUT = timestr_to_secs(timeout)
-        url = self._get_agent_address(name_contains, accept_old)
+        if (RemoteSwingLibrary.APPORT):
+            url = '127.0.0.1:'+RemoteSwingLibrary.APPORT
+        else:
+            url = self._get_agent_address(name_contains, accept_old)
         logger.info('connecting to started application at %s' % url)
```

But this is an unnecessary limitation, could easily introduceRemoteSwingLibrary.APHOST with default value 127.0.0.1
The way I would like to use is running the robot test on a linux machine (a Jenkins build slave) and testing a background swing application (yes, such things exist) on a remote Windows machine which does not have SSH, Cygwin, etc. installed.

**Comment by jakubkorepta** [comment]
Good point suzukieng. I will close this pull and make another with aphost functionality.

**Comment by suzukieng** [comment]
Cool, thank you!

**Comment by suzukieng** [comment]
@jussimalinen Any chance we can include this in master?

**Comment by jussimalinen** [comment]
right, this issue was sort of left hanging because I think @jakubkorepta is no longer working with Nokia for whom he was doing this. Anyway, I will include this in the next release.

**Comment by suzukieng** [comment]
Awesome, thanks.

**Comment by stasiek** [comment]
I'm closing the PR sice we won't be merging it.
@suzukieng the functionality is added in another pull request ( Reconnecting to open app #39 ) and will be present in upcomming release.

**Pull request closed without merging**
