### PR TITLE
New test launching script.

### PR DESCRIPTION
**Pull request by stasiek**
Added test launching script for robotframework/remoteswinglibrary#34
BUILD.rest updated with Testing

### CODE REVIEW

**Comment by jussimalinen** [comment]
Thanks! A couple of notes: This does not work nicely with pyenv (the pybot script for some reason does not work if executed using a different interpreter) and also if the interpreter is not named exactly as expected (I dont have interpreter named python2 by default).

The method for finding remoteswinglibrary version has a small bug: the `lstrip` and `rstrip` take list of characters to remove. So they will remove from version `2.0.4dev` the `ev` and we end up with invalid pythonpath.

Maybe the script could be just directly executable with the interpreter you want to test with?

As in:

```
python3.5 run_atest.py
jython run_atest.py --nobuild
```

And then the script would build the executable (unless --nobuild was used) and then as last thing say:

```python
from robot import run_cli
run_cli(my arguments)
```

This would also return the result code from the execution and make the script more CI friendly. I could then write to jenkins:

```
python3.5 run_atest.py
python2.6 run_atest.py --nobuild
python2.7 run_atest.py --nobuild
jython run_atest.py --nobuild
```

And the execution would stop to first row returning rc != 0.

If you want to keep the current functionality you could maybe consider all strings which dont start with -- as interpreters? So I could then execute with interpreters python2.6 and python2.7 as needed. For executing maybe just executing the interpreter as
```
call([interpreter, "-m", "robot.run",  "--loglevel", "DEBUG", test_path])
```

**Comment by stasiek** [comment]
When I'm looking at commit history, something weird happened there. oO
BUT
@jussimalinen check if it's working for You now. It should.
You can run it as You wanted, just `$ interpreter run_atest.py [--nobuild]`.
I've tested it against multiple pythons and OSes.

**Comment by jussimalinen** [comment]
Brilliant! Thanks!

**Comment by jussimalinen** [comment]
Sorry I have been busy. In general if it takes this long form me to respond to a pr, you guys can also just review and merge it within you team... Especially if need the functionality.

**Pull request merged**
